### ISSUE TITLE
Breed algorithm implementation

### ISSUE THREAD

**Issue by bcwein** [bcwein/DAT540-EvolutionaryANN#1]
Currenty the code is able to generate a specified number of agents and initializing the weights in the neural network, as well as calculating the different agents score.

The next step is to select the parents who got the highest score and create new agents thorugh
- [x] #2 Crossover and
- [x] #3 Mutation
operatons which also needs implementation.

**Comment by sorensenmarius** [comment]
Tenker du at denne tasken bare er en samling av #2 og #3 eller er det noe mer vi må gjøre her? @bcwein

**Comment by bcwein** [comment]
@sorensenmarius Det er ein samling av #2 og #3.

Men når disse 2 issuene er closed bør hovudskriptet utvides sånn at det genererer ein ny generasjon med nevrale nettverk.

**Comment by bcwein** [comment]
Latest pull request now contains crossover and mutation. Closing issue.
