### ISSUE TITLE
Improve crossover breeding

### ISSUE THREAD

**Issue by HGodal** [bcwein/DAT540-EvolutionaryANN#11]
The crossover function implemented is based on randomly choosing genes from parent 1 and parent 2.

**Comment by bcwein** [comment]
Crossover should breed two children instead of just one.

**Comment by johannakinstad** [comment]
https://towardsdatascience.com/introduction-to-optimization-with-genetic-algorithm-2f5001d9964b

**Comment by HGodal** [comment]
The crossover now breeds two children instead of just one
