### ISSUE TITLE
Improve mutation

### ISSUE THREAD

**Issue by johannakinstad** [bcwein/DAT540-EvolutionaryANN#18]

**Comment by bcwein** [comment]
Current mutation algorithm uses a swap approach. Several other approaches exists.

This should preferrably be implemented as an option one sends as a parameter.

example:

mutation(weights, method="swap")
mutation(weights, method="other method")

**Comment by johannakinstad** [comment]
https://towardsdatascience.com/introduction-to-optimization-with-genetic-algorithm-2f5001d9964b

**Comment by ovejorgensen** [comment]
Will try the following methods:
- Scramble Mutation
- Inversion Mutation

**Comment by johannakinstad** [comment]
Methods currently implemented work better with the new dynamic mutation rate
