### ISSUE TITLE
Fix average network

### ISSUE THREAD

**Issue by HGodal** [bcwein/DAT540-EvolutionaryANN#22]
The current average network is based on the average of the next generation only. That is, if we run 15 generations, the average is based on generation 16. This should be changed to the average across all generations.

**Comment by bcwein** [comment]
👍

**Comment by sorensenmarius** [comment]
I'm pretty sure the average network is just run on the last created generation, which is the 15th. But it might be better to average all the generations ;)

**Comment by ovejorgensen** [comment]
Yes it calculates for the last generation now as that is how I interpreted the task, although it should not be hard to change it to run for all gens.

**Comment by bcwein** [comment]
I think that averaging the weights and biases of the last generation makes most sense.

One would expect that the populations get increasingly better over time and at the end, we take the average of the population to get a agent that best describes the population.

Averaging across all generations will include the agents that performed poorly and did not get to reproduce in a previous stage. But our project report can have a discussion for which approach works best, based on collected data.
