### ISSUE TITLE
Introduce diversity in initial population.

### ISSUE THREAD

**Issue by bcwein** [bcwein/DAT540-EvolutionaryANN#25]
Antorweep have told us that one reason for our high scores when mutation rate is quite high is a lack of diversity in the weights and biases of the initial population.

One way that he suggested to combat this was to create diverse weights by not partially fitting the initial population on random samples of observations and actions. but rather choosing random weights between -2 to 2 (no probability distribution specified)

**Comment by sorensenmarius** [comment]
I tried to add randomness by simply overwriting the coefficients and the intercepts when creating a new network, but the results were way worse than what we already have. See the code to see the simple implementation. 

```
    network = MLPClassifier(
        batch_size=1,
        max_iter=1,
        solver='sgd',
        activation='relu',
        learning_rate='invscaling',
        hidden_layer_sizes=4,
        random_state=1
    ).partial_fit(np.array([env.observation_space.sample()]),
                  np.array([env.action_space.sample()]),
                  classes=np.arange(env.action_space.n))


    network.coefs_ = [np.random.rand(4,4)*4-2, np.random.rand(4)*4-2]
    network.intercepts_ = [np.random.rand(4)*4-2, np.random.rand(1)*4-2]


    return network
```
I might have misunderstood what Antorweep meant or how to use it, but this didn't make it any better at least. Just run the branch to see the results.

**Comment by bcwein** [comment]
Can confirm that randomising weights and biases using np.random.rand does not yield good results.

Closing issue.
