### ISSUE TITLE
Mutation operation implementation

### ISSUE THREAD

**Issue by bcwein** [bcwein/DAT540-EvolutionaryANN#3]
Need to implement a mutation operation function for generating new offspring.

See https://en.wikipedia.org/wiki/Mutation_(genetic_algorithm)

**Comment by bcwein** [comment]
Mutation algorithm now swap two weights for a single neural network. This is done across all agents with probability = mutation_rate. 

The algorithm should be expanded to swap biases also. Further we should try different approaches for mutation.

**Comment by johannakinstad** [comment]
Swap mutation version is working
