### ISSUE TITLE
Request: Objectifying script.

### ISSUE THREAD

**Issue by bcwein** [bcwein/DAT540-EvolutionaryANN#41]
Instead of a running the python script in terminal. Maybe we should "objectify" our work to a class.
This will make it easier to run the code and extract performance metrics.
For example a use case will be: visualising different implementations in a notebook.

I imagine a module called cartpoleevolution (or something similar)

Where we have methods like:

cartpoleevolution.simulate(generations=15, population_size=50, crossover="Swap",  ...)
This method return a dataframe of metrics.

cartpoleevolution.render()
Render a successfull simulation for display.

etc.

Is this a good idea for further work?

**Comment by sorensenmarius** [comment]
👍

**Comment by johannakinstad** [comment]
👍

**Comment by bcwein** [comment]
Creating branch #41 and start developing the class cartpoleevolution.
