### ISSUE TITLE
Review cartpoleevolution class

### ISSUE THREAD

**Issue by bcwein** [bcwein/DAT540-EvolutionaryANN#44]
The new cartpoleevolution class is now created.

There are still some functionality that is missing:

- [ ] render method

Functions that are currently in the class should be reviewed and altered to follow object-oriented practices.
- [ ] breedCrossover
- [ ] mutation_W_B
- [ ] mutation_rate
- [ ] simulate

Also, missing methods from functions.py should be added.

Feel free to add new methods also.

**Comment by sorensenmarius** [comment]
We should probably rename the class to use CamelCase as well

**Comment by bcwein** [comment]
Closing this due to Pull Request #52 where i have discarded this class.

I chose to do this because:
- It was difficult to translate our code to true object-oriented practices
- Functionality was missing from the class
- Simply due to time.
